### PR TITLE
Update most of the un-translated french strings.

### PR DESCRIPTION
**Pull request by YaelBx**
Correct some mistakes and use some more common words.

Signed-off-by: Yaël Boutreux <yael.boutreux@gmail.com>

### CODE REVIEW

**Comment by YaelBx** [comment]
@samboowoo Since it seems that you're also french, feel free to comment if you have any objections on the submitted modifications ;)

**Review by samboowoo — COMMENTED** [review]
Hi,
I've checked the different french propositions.
They are not wrong but the previous translations are more used in this special case.
Some characters like \ also are needed for a good display in app. Some terms are also translated but not yet implemented in current version.
Kind regards,
Sam

**Comment by YaelBx** [comment]
> Some characters like \ also are needed for a good display in app. 

You might have check only the first commit and not the diff between my branch and master, if you are refering to " ' "all of them have their " \ ". 

> They are not wrong but the previous translations are more used in this special case.

@samboowoo can you then be more specific on what to keep and what to throw in your opinion ?
https://github.com/Pittvandewitt/Wavelet-strings/pull/18/files

**Comment by samboowoo** [comment]
OK, I've checked all terms and they are correct for me  (you know what means synonims ...)
For a better display in app the choice is to contract at maximum terms and sentences.
Also, É and E can be used the same and it's just a simple point of view. Important is to keep the same behaviour for all terms.
All of this is not really important and I don't want to lost more time about that.

**Comment by YaelBx** [comment]
Hi,
if no more activity/updates then I'll close this PR next week.

**Comment by samboowoo** [comment]
Hi,
In fact,  I've just changed the É
It's visible in the last version.

**Comment by YaelBx** [comment]
Hi @samboowoo, hope you're well :)

`In fact, I've just changed the É
It's visible in the last version.`
Looking at my PR diff with the master branch it doesn't seems like it, but I might be missing something.

I agree with your point about synonyms, but I still think that the ones in this PR are more accurate (like `intensité` instead of `force` in the audio world) or commonly used (`appareil auditif` instead of `aide auditive`). If this makes the app UI odd (because of a string too long) then I agree we should stick to the current translations. 

For É/E I agree this is really nitpicking, both are really well accepted.

`Transitoires` is the official term for acoustic engineering, but in the music production world the english word is also commonly used, so it's OK for me if we keep the english word.

Still, `aigus` is a common french mistake and must be corrected to `aiguës`.

Sorry if it is bothering, I just want to avoid a stalled PR.
Have a nice day !

**Comment by samboowoo** [comment]
Hi,
I prefer keep current terms. It's necessary to have the shortest terms as possible for various and small devices screens. I assume also the term aigus.

**Comment by YaelBx** [comment]
OK, then no changes needs to be done, I close this PR, thank you

**Pull request closed without merging**
