### PR TITLE
French translation   fr-strings

### PR DESCRIPTION
**Pull request by samboowoo**
Hello Thomas,
French translation is finished. Hope you can implemente it soon. Thanks.
[fr-strings.txt](https://github.com/Pittvandewitt/Wavelet-strings/files/5838977/fr-strings.txt)

### CODE REVIEW

**Comment by Pittvandewitt** [comment]
There doesn't seem to be any error with the special characters and the escapes are placed correctly too, which is great.
I do have 3 remarks however.
The first one is about the warning_library_null string. %s will be replaced with 'Reverberation' for example. With this in mind, would that change the grammer? Something like: Wavelet n\'a pas pu instancier les effets %s ?
Second is about the menu_legacy_mode string. Since legacy mode does (partially) not work on all devices, I would prefer if it could be translated to deprecated mode instead of global mode if legacy mode cannot be translated directly to French.
The last remark is that the translated file should be named strings.xml and placed in a new folder called values-fr.

Thank you very much for your effort so far!

**Comment by samboowoo** [comment]
Hello Thomas,
In fact, it's better to keep the term "Legacy" because used also in french and often related in help guide.
Minor changements also accordingly after your remarks about s%
New file strings.txt (sorry, i'm not able to attach a xml file).
[strings.txt](https://github.com/Pittvandewitt/Wavelet-strings/files/5845667/strings.txt)

**Comment by samboowoo** [comment]
Error (wrong file) sorry, you have to use this file attached.
[strings.txt](https://github.com/Pittvandewitt/Wavelet-strings/files/5845794/strings.txt)

**Comment by samboowoo** [comment]
Hello Thomas,
In fact, it's better to keep the term "Legacy" because used also in french and often related in help guide.
Minor changements also accordingly after your remarks about s%
New file strings.txt (sorry, i'm not able to attach a xml file).
[strings.txt](https://github.com/Pittvandewitt/Wavelet-strings/files/5845796/strings.txt)

**Pull request closed without merging**
